### ISSUE TITLE
New release to support react 16

### ISSUE THREAD

**Issue by kachkaev** [kciter/react-barcode#10]
Hi @kciter. Great to see React 16 support on master after https://github.com/kciter/react-barcode/pull/9 is merged! Could you please publish a new version on npm? As of now, the latest is still from Aug 2016.

Cheers!

**Comment by kciter** [comment]
I published. I'm sorry too late. 😢 
Thank you!

**Comment by kachkaev** [comment]
Awesome, many thanks!
