### ISSUE TITLE
TypeError: Cannot add property text, object is not extensible

### ISSUE THREAD

**Issue by JackyLee1116** [kciter/react-barcode#17]
i got this error "TypeError: Cannot add property text, object is not extensible"
from generating barcode

my barcode template:
<Barcode
 value={'123'}
 margin={0}
 height={35}
 fontSize={0}
/>

react version: 15.5.4

anyone can help me? thanks~

**Comment by kciter** [comment]
Bug fixed.
Just update 1.3.1 :)

**Comment by JackyLee1116** [comment]
but some setting attribute is  not working on the barcode template

**Comment by ggsjyoon** [comment]
Looks like some props are not working in `v1.3.1`. In my case, `width` and `height` options are not working.
