### ISSUE TITLE
Module not found: create-react-class

### ISSUE THREAD

**Issue by oonsamyi** [kciter/react-barcode#21]
I have installed react-barcode with yarn: `yarn add react-barcode`.
Then I connected this library in my project, collected the project with webpack and received the following error:

> ERROR in ./node_modules/react-barcode/lib/react-barcode.js
Module not found: Error: Can't resolve 'create-react-class' in '/home/user/projects/best-project/node_modules/react-barcode/lib'

This error occurs because  'create-react-class' is in devDependencies.
Also there is 'react-props', which is used in the main library file.

**Comment by oonsamyi** [comment]
#22

**Comment by kciter** [comment]
1.3.3 update published.
