### ISSUE TITLE
npm modules not updated

### ISSUE THREAD

**Issue by Muljayan** [kciter/react-barcode#31]
I wanted to render the barcode in an img tag and realized that nothing gets rendered. 

Upon checking the installed react-barcode  in node_modules i realized that the react-barcode.js file is still written using the createClass syntax and doesn't look like the  react-barcode.js file in this repo.

**Comment by aakash-bhatia-arkade** [comment]
Hey Noticed the same thing:

  render: function render() {
    if (this.props.renderer === 'svg') {
      return React.createElement('svg', { ref: 'renderElement' });
    } else if (this.props.renderer === 'canvas') {
      return React.createElement('canvas', { ref: 'renderElement' });
    } else if (this.props.renderer === 'img') {
      return React.createElement('img', { ref: 'renderElement' });
    }
  }

It's a great package, hope it's updated to match the repo.

**Comment by abrenoch** [comment]
I want to +1 this!

**Comment by Svennisen** [comment]
+1 !!

**Comment by SeanCannon** [comment]
Just put the github url in your package.json : 
![image](https://user-images.githubusercontent.com/991478/69115769-a6264f00-0a3e-11ea-9db2-85ac126a7da6.png)

**Comment by alandraper** [comment]
Yeah. The github has been updated last month, but the npm module is 5 months old.
