### ISSUE TITLE
Responsive Barcode ?

### ISSUE THREAD

**Issue by AlexDemzz** [kciter/react-barcode#32]
Hello,
Is it possible to use % instead of px or maybe put a className for the width ?

**Comment by HuntBurdick** [comment]
Seems to work well responsively by adding a wrapper with a class in Chrome but not so much in Firefox. The barcode does not respect the width of the parent.

**Comment by HuntBurdick** [comment]
Never mind. Got this to work by adding a parent wrapper div with width 100% and then targeting the outputted SVG with width 100% and height auto CSS styling.

**Comment by AlexDemzz** [comment]
> Never mind. Got this to work by adding a parent wrapper div with width 100% and then targeting the outputted SVG with width 100% and height auto CSS styling.

Smart idea !

**Comment by famoso96** [comment]
Quieres hacer la barra responsive, la opcion mas rapida y sin preocuparte por como queda es usar TableContainer de MaterialUI, te dejo en mi casi mi ejemplo que me quedo 100% responsive.
 <TableContainer>
      <Barcode
          value={codigoBarras}
          format="CODE39"
          width={1}
          height={30}
          {...config}    
      />
 </TableContainer>

Saludos!!!
