### ISSUE TITLE
Wrong if make error in React 16.12.0 :D

### ISSUE THREAD

**Issue by lphuctai** [kciter/react-barcode#38]
https://github.com/kciter/react-barcode/blob/e45c88d0c32f21607459958d7aa64ff23e053d7c/src/react-barcode.js#L11

Hi, I just recognize this condition difference with commend above.
This condition coincident matches with React version 16.**12**.0.

**Comment by sebasegura97** [comment]
Everything was working fine in my computer but i need to change it, when i move to the new pc i had this error:

![Captura de pantalla 2019-11-15 a la(s) 12 59 11](https://user-images.githubusercontent.com/31363025/68956946-d6a08b80-07a7-11ea-9e9a-80ed738d1077.png)

And i'm pretty sure i used the same dependencies version.

I just deleted: `|| version[1] === '12'`

![Captura de pantalla 2019-11-15 a la(s) 13 01 15](https://user-images.githubusercontent.com/31363025/68957071-094a8400-07a8-11ea-8c31-e237a19ca2e9.png)

And it worked for me. But i think that it is not the right way.

Any suggestion?  I never contributed (i'm junior) but i really like to start now!

**Comment by colepanike** [comment]
Found this as well. PR inbound.

**Comment by colepanike** [comment]
Looks like my PR is not needed. #39 fixes it the same way

**Comment by colepanike** [comment]
This can now be closed with the merge of #39

**Comment by kachkaev** [comment]
We are still waiting for a release on npm 🙏 [The latest version](https://www.npmjs.com/package/react-barcode?activeTab=versions) is more than one year old.

**Comment by kciter** [comment]
@colepanike @kachkaev @lphuctai @sebasegura97 
Completed 1.4.0 release.

**Comment by colepanike** [comment]
Awesome! Would you mind closing this issue then? Thanks for the module man!

**Comment by sebasegura97** [comment]
Thanks!
