### ISSUE TITLE
Update NPM Registry

### ISSUE THREAD

**Issue by paytonagreen** [kciter/react-barcode#59]
Could someone with the appropriate access update the NPM registry entry to v 1.4.1 as seen in this repo?

Would love to get React 17 support/not have to do a SKIP_PREFLIGHT_CHECK on the env to avoid errors, especially since the code's already been updated. Thanks in advance for any help!

**Comment by kciter** [comment]
1.4.1 updated. Sorry to be late.
https://www.npmjs.com/package/react-barcode

**Comment by paytonagreen** [comment]
Thank you! Appreciate your work on this lib!
