### ISSUE TITLE
Add React ^18.0.0 support

### ISSUE THREAD

**Issue by JeffreyStevens** [kciter/react-barcode#69]
Hello! 

Thank you for this package. Is it possible to merge the React version pull request so we can remove the --legacy-peer-deps flag from our Azure build process? I never needed that until I added this package to our app.

Thank you.

**Comment by JeffreyStevens** [comment]
The new 1.4.2 version does have React 18 in it but I still get errors because I am at 18.2.0 and the merged code only allows for 18.0.0.

`npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^17.0.0 || 18.0.0" from react-barcode@1.4.2
npm ERR! node_modules/react-barcode
npm ERR!   react-barcode@"1.4.2" from the root project
`

**Comment by martindebrunne** [comment]
Hi ! I got the same error ;) Could you fix this issue please ?

**Comment by xersuy** [comment]
Hello ! Same Err

**Comment by kciter** [comment]
1.4.5 updated. I'm sorry too late.
