### ISSUE TITLE
Plans to support for React v16

### ISSUE THREAD

**Issue by miguelalvarezi** [kciter/react-barcode#8]
Hi, as you probably know, 

> React.createClass is deprecated and will be removed in version 16

Do you have any plans to support v16 of React?

Thanks!

**Comment by adrianojdesouza** [comment]
@miguelalvarezi I am needing it too

**Comment by kachkaev** [comment]
@kciter could you please consider replacing React.createClass similar to how it's done here?
https://github.com/jossmac/react-scrolllock/pull/5/files

Just discovered your project today and found it great! Would be cool if it did not generate the warning and was compatible with React 16, which might be released pretty soon!

**Comment by adrianojdesouza** [comment]
@kciter I created a [PR to that](https://github.com/kciter/react-barcode/pull/9)
