### ISSUE TITLE
CHANGELOG.md / GitHub releases

### ISSUE THREAD

**Issue by kachkaev** [kciter/react-barcode#94]
👋 @kciter!

I’m using `react-barcode` in one of my projects, it’s been there for a while. Today I read about `react-barcode@1.5.0` in [React Status](https://react.statuscode.com/issues/376) and wanted to check what was new.

![Screenshot 2024-03-07 at 15 35 30](https://github.com/kciter/react-barcode/assets/608862/8a67f56f-c938-434b-bcf3-6e16497ff74d)

Unfortunately I could not find CHANGELOG.md or anything in https://github.com/kciter/react-barcode/releases which left me a bit confused.

It’d be great if you could summarise the changes and publish them. I know it’s possible to look at commit history etc, but this requires more skills and time. If there is a proper CHANGELOG entry, repo tools like [Renovate Bot](https://github.com/renovatebot/renovate) can pick them too!

----

**PS** Congrats on the release and on the mention in React Status! 🎉

**Comment by kciter** [comment]
Thank you for your congrats. :smile: 
I just wrote release notes with GitHub's auto-generated.

https://github.com/kciter/react-barcode/releases/tag/1.5.0

In summary, update dependencies, add missing types, and add id and className props in 1.5.0.

**Comment by kachkaev** [comment]
Great, thank you! 🙌
